import { useEffect, useState } from 'react';
import { competitionApi, directoryApi } from '../api';
import { toInstant, toLocalInput } from '../utils';
import { Alert } from './Ui';

function defaults() {
  const start = new Date(Date.now() + 7 * 86400000); const end = new Date(start.getTime() + 3 * 3600000);
  return { title: '', level: 'REGIONAL', disciplineId: '', startsAt: toLocalInput(start), endsAt: toLocalInput(end), format: 'ONLINE', venue: '', description: '', registrationOpensAt: toLocalInput(new Date(Date.now() + 3600000)), registrationClosesAt: toLocalInput(new Date(start.getTime() - 3600000)), rules: '' };
}

export default function CompetitionForm({ competition, onSaved }) {
  const [form, setForm] = useState(competition ? { ...competition, disciplineId: String(competition.disciplineId), startsAt: toLocalInput(competition.startsAt), endsAt: toLocalInput(competition.endsAt), registrationOpensAt: toLocalInput(competition.registrationOpensAt), registrationClosesAt: toLocalInput(competition.registrationClosesAt) } : defaults());
  const [disciplines, setDisciplines] = useState([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { directoryApi.disciplines().then(setDisciplines).catch((e) => setError(e.message)); }, []);
  const field = (name) => (event) => setForm({ ...form, [name]: event.target.value });
  async function submit(event) { event.preventDefault(); setBusy(true); setError(''); try { const body = { title: form.title, level: form.level, disciplineId: Number(form.disciplineId), startsAt: toInstant(form.startsAt), endsAt: toInstant(form.endsAt), format: form.format, venue: form.venue || null, description: form.description, registrationOpensAt: toInstant(form.registrationOpensAt), registrationClosesAt: toInstant(form.registrationClosesAt), rules: form.rules, ...(competition ? { version: competition.version } : {}) }; onSaved(competition ? await competitionApi.update(competition.id, body) : await competitionApi.create(body)); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  return <form className="form-grid" onSubmit={submit}><Alert>{error}</Alert><label className="span-2">Название<input required maxLength="200" value={form.title} onChange={field('title')} /></label><label>Уровень<select value={form.level} onChange={field('level')}><option value="REGIONAL">Региональный</option><option value="DAGESTAN_CHAMPIONSHIP">Чемпионат Дагестана</option><option value="INTERREGIONAL">Межрегиональный</option><option value="NATIONAL">Всероссийский</option><option value="RUSSIAN_CHAMPIONSHIP">Чемпионат России</option></select></label><label>Дисциплина<select required value={form.disciplineId} onChange={field('disciplineId')}><option value="">Выберите</option>{disciplines.map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Начало<input type="datetime-local" required value={form.startsAt} onChange={field('startsAt')} /></label><label>Окончание<input type="datetime-local" required value={form.endsAt} onChange={field('endsAt')} /></label><label>Открытие регистрации<input type="datetime-local" required value={form.registrationOpensAt} onChange={field('registrationOpensAt')} /></label><label>Закрытие регистрации<input type="datetime-local" required value={form.registrationClosesAt} onChange={field('registrationClosesAt')} /></label><label>Формат<select value={form.format} onChange={field('format')}><option value="ONLINE">Онлайн</option><option value="OFFLINE">Очно</option><option value="HYBRID">Гибрид</option></select></label><label>Место проведения<input maxLength="500" value={form.venue || ''} onChange={field('venue')} placeholder="Для онлайн можно оставить пустым" /></label><label className="span-2">Описание<textarea required maxLength="5000" rows="5" value={form.description} onChange={field('description')} /></label><label className="span-2">Правила<textarea required maxLength="5000" rows="6" value={form.rules} onChange={field('rules')} /></label><div className="form-actions span-2"><button className="btn-primary" disabled={busy}>{busy ? 'Сохраняем…' : competition ? 'Сохранить' : 'Создать черновик'}</button></div></form>;
}
