import { useCallback, useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { competitionApi, contestApi } from '../api';
import CompetitionForm from '../components/CompetitionForm';
import TaskForm from '../components/TaskForm';
import { Alert, Empty, Loader, Modal, PageTitle, StatusBadge } from '../components/Ui';
import { Standings } from './CompetitionPage';
import { formatDate } from '../utils';

const transitions = { DRAFT: ['UPCOMING', 'CANCELLED'], UPCOMING: ['ONGOING', 'COMPLETED', 'CANCELLED'], ONGOING: ['COMPLETED', 'CANCELLED'] };
const transitionLabels = { UPCOMING: 'Опубликовать', ONGOING: 'Начать', COMPLETED: 'Завершить', CANCELLED: 'Отменить' };

export default function OrganizerCompetitionPage() {
  const { id } = useParams(); const navigate = useNavigate();
  const [competition, setCompetition] = useState(null); const [tasks, setTasks] = useState([]); const [participants, setParticipants] = useState([]); const [submissions, setSubmissions] = useState([]); const [standings, setStandings] = useState(null); const [tab, setTab] = useState('overview'); const [modal, setModal] = useState(null); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { setError(''); try { const current = await competitionApi.management(id); setCompetition(current); const [taskResult, peopleResult, submissionResult, standingResult] = await Promise.allSettled([contestApi.managementTasks(id), competitionApi.participants(id), contestApi.submissions(id, { size: 100 }), current.finalizedAt ? contestApi.standings(id) : Promise.resolve(null)]); setTasks(taskResult.value || []); setParticipants(peopleResult.value?.content || []); setSubmissions(submissionResult.value?.content || []); setStandings(standingResult.value || null); } catch (e) { setError(e.message); } }, [id]);
  useEffect(() => { load(); }, [load]);
  const taskMap = useMemo(() => new Map(tasks.map((item) => [item.id, item])), [tasks]); const peopleMap = useMemo(() => new Map(participants.map((item) => [item.id, item.athlete])), [participants]);
  async function changeStatus(status) { if (!confirm(`${transitionLabels[status]} соревнование?`)) return; setBusy(true); try { const saved = await competitionApi.changeStatus(id, status, competition.version); setCompetition(saved); setNotice(`Статус изменён: ${transitionLabels[status]}`); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  async function removeCompetition() { if (!confirm('Удалить черновик без возможности восстановления?')) return; try { await competitionApi.remove(id, competition.version); navigate('/organizer'); } catch (e) { setError(e.message); } }
  async function removeTask(task) { if (!confirm(`Удалить задание «${task.title}»?`)) return; try { await contestApi.removeTask(id, task.id, task.version); load(); } catch (e) { setError(e.message); } }
  async function finalize() { if (!confirm('Опубликовать итоговую таблицу и результаты спортсменов?')) return; setBusy(true); try { const result = await contestApi.finalize(id); setStandings(result); setNotice('Итоги опубликованы, рейтинг пересчитан'); await load(); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  if (!competition && !error) return <main className="page"><Loader /></main>;
  return <main className="page"><Alert>{error}</Alert><Alert type="success">{notice}</Alert>{competition && <><div className="back-link"><Link to="/organizer">← Все соревнования</Link></div><PageTitle eyebrow="Управление соревнованием" title={competition.title} subtitle={`${formatDate(competition.startsAt, true)} — ${formatDate(competition.endsAt, true)}`} actions={<StatusBadge value={competition.status} />} />
    <div className="management-actions">{(transitions[competition.status] || []).map((status) => <button key={status} className={status === 'CANCELLED' ? 'btn-danger' : 'btn-primary'} disabled={busy} onClick={() => changeStatus(status)}>{transitionLabels[status]}</button>)}{competition.status === 'COMPLETED' && !competition.finalizedAt && <button className="btn-primary" disabled={busy} onClick={finalize}>Опубликовать итоги</button>}<Link className="btn-ghost" to={`/competitions/${id}`}>Публичная страница</Link></div>
    <nav className="tabs"><button className={tab === 'overview' ? 'active' : ''} onClick={() => setTab('overview')}>Обзор</button><button className={tab === 'tasks' ? 'active' : ''} onClick={() => setTab('tasks')}>Задания <span>{tasks.length}</span></button><button className={tab === 'participants' ? 'active' : ''} onClick={() => setTab('participants')}>Участники <span>{participants.length}</span></button><button className={tab === 'submissions' ? 'active' : ''} onClick={() => setTab('submissions')}>Решения <span>{submissions.length}</span></button><button className={tab === 'standings' ? 'active' : ''} onClick={() => setTab('standings')}>Итоги</button></nav>
    {tab === 'overview' && <Overview competition={competition} onEdit={() => setModal({ type: 'competition' })} onDelete={removeCompetition} tasks={tasks} participants={participants} submissions={submissions} />}
    {tab === 'tasks' && <Tasks tasks={tasks} editable={competition.status === 'DRAFT' || competition.status === 'UPCOMING'} onAdd={() => setModal({ type: 'task' })} onEdit={(task) => setModal({ type: 'task', task })} onDelete={removeTask} />}
    {tab === 'participants' && <Participants participants={participants} />}
    {tab === 'submissions' && <Submissions submissions={submissions} tasks={taskMap} people={peopleMap} onReview={(submission) => setModal({ type: 'review', submission })} />}
    {tab === 'standings' && (standings ? <Standings standings={standings} /> : <Empty title="Итоги ещё не опубликованы" text="Завершите соревнование, проверьте все решения и нажмите «Опубликовать итоги»." />)}
  </>}{modal?.type === 'competition' && <Modal title="Параметры соревнования" wide onClose={() => setModal(null)}><CompetitionForm competition={competition} onSaved={(saved) => { setCompetition(saved); setModal(null); }} /></Modal>}{modal?.type === 'task' && <Modal title={modal.task ? 'Редактирование задания' : 'Новое задание'} wide onClose={() => setModal(null)}><TaskForm competitionId={Number(id)} task={modal.task} onSaved={() => { setModal(null); load(); }} /></Modal>}{modal?.type === 'review' && <Modal title="Проверка решения" wide onClose={() => setModal(null)}><ReviewForm competitionId={id} submission={modal.submission} task={taskMap.get(modal.submission.taskId)} athlete={peopleMap.get(modal.submission.registrationId)} onSaved={() => { setModal(null); load(); }} /></Modal>}</main>;
}

function Overview({ competition, onEdit, onDelete, tasks, participants, submissions }) {
  return <div className="dashboard-grid"><section className="panel span-2 prose"><div className="panel-head"><h2>Описание и правила</h2>{['DRAFT', 'UPCOMING'].includes(competition.status) && <button className="btn-ghost btn-small" onClick={onEdit}>Редактировать</button>}</div><p>{competition.description}</p><h3>Правила</h3><p className="pre-line">{competition.rules}</p></section><section className="panel"><h2>Готовность</h2><div className="check-list"><span className="done">✓ Описание заполнено</span><span className={tasks.length ? 'done' : ''}>{tasks.length ? '✓' : '○'} Добавлено заданий: {tasks.length}</span><span className={participants.length ? 'done' : ''}>{participants.length ? '✓' : '○'} Участников: {participants.length}</span><span className={submissions.length && submissions.every((s) => s.status === 'REVIEWED') ? 'done' : ''}>○ Проверено решений: {submissions.filter((s) => s.status === 'REVIEWED').length}/{submissions.length}</span></div>{competition.status === 'DRAFT' && <button className="btn-danger full" onClick={onDelete}>Удалить черновик</button>}</section></div>;
}

function Tasks({ tasks, editable, onAdd, onEdit, onDelete }) {
  return <section className="panel"><div className="panel-head"><div><h2>Задания соревнования</h2><p>Для публикации требуется хотя бы одно задание.</p></div>{editable && <button className="btn-primary" onClick={onAdd}>+ Добавить задание</button>}</div>{tasks.length ? <div className="task-list management">{tasks.map((task, index) => <article className="task-card" key={task.id}><div className="task-number">{index + 1}</div><div className="task-body"><div className="task-title"><h3>{task.title}</h3><span>{task.maxPoints} баллов</span></div><p className="pre-line">{task.statement}</p>{editable && <div className="inline-actions"><button className="btn-ghost btn-small" onClick={() => onEdit(task)}>Изменить</button><button className="btn-danger btn-small" onClick={() => onDelete(task)}>Удалить</button></div>}</div></article>)}</div> : <Empty title="Добавьте первое задание" text="Без задания соревнование нельзя опубликовать." />}</section>;
}

function Participants({ participants }) {
  return <section className="panel"><div className="panel-head"><h2>Зарегистрированные участники</h2></div>{participants.length ? <div className="table-wrap flat"><table><thead><tr><th>Спортсмен</th><th>Город</th><th>Организация</th><th>Квалификация</th><th>Дата заявки</th></tr></thead><tbody>{participants.map((item) => <tr key={item.id}><td><Link to={`/athletes/${item.athleteId}`}>{item.athlete?.fullName || `#${item.athleteId}`}</Link></td><td>{item.athlete?.city || '—'}</td><td>{item.athlete?.organization || '—'}</td><td>{item.athlete?.qualification || '—'}</td><td>{formatDate(item.registeredAt, true)}</td></tr>)}</tbody></table></div> : <Empty title="Заявок пока нет" />}</section>;
}

function Submissions({ submissions, tasks, people, onReview }) {
  return <section className="panel"><div className="panel-head"><h2>Решения участников</h2></div>{submissions.length ? <div className="submission-grid">{submissions.map((item) => <article key={item.id} className="submission-card"><div><StatusBadge value={item.status} /><small>{formatDate(item.submittedAt, true)}</small></div><h3>{tasks.get(item.taskId)?.title || `Задание #${item.taskId}`}</h3><p>{people.get(item.registrationId)?.fullName || `Заявка #${item.registrationId}`}</p><pre>{item.answer}</pre><div className="card-footer"><span>{item.points == null ? 'Баллы не выставлены' : `${item.points} баллов`}</span><button className="btn-primary btn-small" onClick={() => onReview(item)}>{item.status === 'REVIEWED' ? 'Изменить оценку' : 'Проверить'}</button></div></article>)}</div> : <Empty title="Решений пока нет" />}</section>;
}

function ReviewForm({ competitionId, submission, task, athlete, onSaved }) {
  const [points, setPoints] = useState(submission.points ?? 0); const [comment, setComment] = useState(submission.reviewComment || ''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(event) { event.preventDefault(); setBusy(true); try { await contestApi.review(competitionId, submission.id, { version: submission.version, points: Number(points), comment: comment || null }); onSaved(); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  return <form className="form-stack" onSubmit={submit}><Alert>{error}</Alert><div className="review-context"><span>Спортсмен</span><strong>{athlete?.fullName || `Заявка #${submission.registrationId}`}</strong><span>Задание</span><strong>{task?.title}</strong></div><label>Ответ<textarea rows="10" readOnly value={submission.answer} /></label><label>Баллы из {task?.maxPoints}<input type="number" min="0" max={task?.maxPoints} required value={points} onChange={(e) => setPoints(e.target.value)} /></label><label>Комментарий<textarea rows="4" maxLength="5000" value={comment} onChange={(e) => setComment(e.target.value)} /></label><div className="form-actions"><button className="btn-primary" disabled={busy}>{busy ? 'Сохраняем…' : 'Сохранить оценку'}</button></div></form>;
}
