import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { athleteApi, competitionApi, ratingApi } from '../api';
import ProfileForm from '../components/ProfileForm';
import { Alert, Empty, Loader, Modal, PageTitle, StatusBadge } from '../components/Ui';
import { formatDate } from '../utils';

export default function ProfilePage() {
  const [profile, setProfile] = useState(undefined); const [results, setResults] = useState([]); const [registrations, setRegistrations] = useState([]); const [rating, setRating] = useState(null); const [history, setHistory] = useState([]); const [contests, setContests] = useState({}); const [edit, setEdit] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async () => { setError(''); try { const current = await athleteApi.mine(); setProfile(current); const settled = await Promise.allSettled([athleteApi.results(current.id), athleteApi.registrations(), ratingApi.current(current.id), ratingApi.history(current.id)]); setResults(settled[0].value?.content || []); const regs = settled[1].value?.content || []; setRegistrations(regs); setRating(settled[2].value || null); setHistory(settled[3].value?.content || []); const loaded = await Promise.all(regs.map((r) => competitionApi.get(r.competitionId).catch(() => null))); setContests(Object.fromEntries(loaded.filter(Boolean).map((c) => [c.id, c]))); } catch (e) { if (e.status === 404) setProfile(null); else setError(e.message); } }, []);
  useEffect(() => { load(); }, [load]);
  if (profile === undefined && !error) return <main className="page"><Loader /></main>;
  if (profile === null) return <main className="page narrow-page"><PageTitle eyebrow="Первый шаг" title="Создайте профиль спортсмена" subtitle="Эти данные будут использоваться в заявках, результатах и рейтинге." /><section className="panel"><ProfileForm onSaved={setProfile} /></section></main>;
  return <main className="page"><Alert>{error}</Alert><PageTitle eyebrow="Личный кабинет" title={profile?.fullName || 'Профиль'} subtitle={`${profile?.city || ''}${profile?.organization ? ` · ${profile.organization.name}` : ''}`} actions={<button className="btn-ghost" onClick={() => setEdit(true)}>Редактировать</button>} />
    <section className="profile-summary"><div className="profile-avatar">{profile.fullName.slice(0, 1)}</div><div><span>Квалификация</span><strong>{profile.qualification?.name || 'Не присвоена'}</strong></div><div><span>Рейтинг</span><strong>{rating?.totalPoints ?? 0}</strong></div><div><span>Результатов</span><strong>{results.length}</strong></div><div><span>Заявок</span><strong>{registrations.length}</strong></div></section>
    <div className="dashboard-grid"><section className="panel span-2"><div className="panel-head"><h2>Мои соревнования</h2><Link to="/competitions">Найти соревнование →</Link></div>{registrations.length ? <div className="compact-list">{registrations.map((r) => <Link key={r.id} to={`/competitions/${r.competitionId}`}><div><strong>{contests[r.competitionId]?.title || `Соревнование #${r.competitionId}`}</strong><span>{formatDate(r.registeredAt, true)}</span></div><StatusBadge value={r.status} /></Link>)}</div> : <Empty title="Заявок пока нет" text="Выберите соревнование и подайте заявку." />}</section>
      <section className="panel"><div className="panel-head"><h2>Рейтинг</h2></div><div className="rating-breakdown"><strong>{rating?.totalPoints ?? 0}</strong><span>итоговых баллов</span><div><small>За результаты</small><b>{rating?.resultPoints ?? 0}</b></div><div><small>За квалификацию</small><b>{rating?.qualificationPoints ?? 0}</b></div></div>{history.length > 1 && <p className="muted center">История содержит {history.length} пересчётов</p>}</section>
      <section className="panel span-3"><div className="panel-head"><h2>Официальные результаты</h2></div>{results.length ? <div className="table-wrap flat"><table><thead><tr><th>Соревнование</th><th>Дата</th><th>Место</th><th>Баллы рейтинга</th></tr></thead><tbody>{results.map((r) => <tr key={r.id}><td><Link to={`/competitions/${r.competitionId}`}>{r.competitionTitle}</Link></td><td>{formatDate(r.competitionStartsAt)}</td><td><strong>#{r.place}</strong></td><td className="gold-text">+{r.ratingPoints}</td></tr>)}</tbody></table></div> : <Empty title="Результатов пока нет" text="После завершения соревнования результат появится здесь автоматически." />}</section></div>
    {edit && <Modal title="Редактирование профиля" onClose={() => setEdit(false)}><ProfileForm profile={profile} onSaved={(saved) => { setProfile(saved); setEdit(false); }} /></Modal>}
  </main>;
}
